apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ali-lotfi-operator
spec:
  group: sample.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                image:
                  type: string
  names:
    kind: HelloWorld
    plural: helloworlds
    singular: helloworld
    shortNames:
      - hw
